name: "test doxygen"

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs/126.2-Documentation-in-github
          folder: .
          config_file: Doxyfile
          doxygen_version: 1.9.6




